M48
; DRILL file {KiCad 7.0.7} date Thu Oct  5 12:14:27 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-05T12:14:27+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.400
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C2.000
%
G90
G05
T1
X5.125Y11.525
X5.125Y8.025
T2
X18.738Y12.125
X18.738Y7.625
T0
M30
